### ISSUE TITLE
数据库的结构能发一下吗？

### ISSUE THREAD

**Issue by TajangSec** [zzw-111-bit/AndroidWork#1]
本地搭建学习，数据库没有结构

**Comment by zhangzhiwei-zzw** [comment]
数据库work中的两个表的建表语句
create table comment
(
	num int auto_increment
		primary key,
	username varchar(20) not null,
	comments varchar(60) not null,
	time date not null,
	position varchar(10) not null,
	imageid varchar(20) null
);

create table user
(
	account varchar(20) not null
		primary key,
	username varchar(20) not null,
	password varchar(20) not null,
	userword varchar(30) null,
	imageid int not null
);

**Comment by TajangSec** [comment]
感谢！

**Comment by TajangSec** [comment]
为什么我建表了，也修改了数据库连接配置，发现界面的帖子，还是原来的？
![Snipaste_2022-05-25_10-00-59](https://user-images.githubusercontent.com/63721558/170163637-f504d5ff-d56b-4f29-9902-952edfdcde34.png)

**Comment by zhangzhiwei-zzw** [comment]
在安卓的主项目中我使用的是远程阿里云的服务器，需要在项目文件中把服务器的ip地址转换为你的本地主机ip127.0.0.1

![image](https://user-images.githubusercontent.com/72742031/170164609-a2b2938f-1461-494d-b4a5-ec5fd0922722.png)

**Comment by TajangSec** [comment]
这个我修改后，显示无法连接127.0.0.1：8080。我是Windows，我需要在本地搭建个什么服务？

**Comment by zhangzhiwei-zzw** [comment]
仓库中EXAM3-6S下是Java Web的代码，在本地运行后发布在Tomcat，如果是无法连接可以查看端口是否被占用，之后重启相关服务试试

**Comment by TajangSec** [comment]
我的tomcat文件夹如下
![Snipaste_2022-05-31_17-12-00](https://user-images.githubusercontent.com/63721558/171138244-0f8cf47b-9a0b-4192-bf4e-7be109c64c10.png)
当我把web下各个Javaweb文件放在exam6s下后，下图引用也是对的
![Snipaste_2022-05-31_17-12-12](https://user-images.githubusercontent.com/63721558/171138451-cc651423-0c61-4572-80dc-77c0ea127f51.png)
可是为什么，出现了java.net连接错误，显示无法连接127.0.0.1：8080，而且我的浏览器都可以访问到

**Comment by TajangSec** [comment]
`http://47.107.68.210:8080/exam3-6sarchive/    `这个下面的文件能发一下吗

**Comment by zhangzhiwei-zzw** [comment]
exam3-6sarchive这个文件是我把项目打成war包之后的文件名称，你刚才问的无法访问的问题，如果使用模拟器访问的话，可以试试把ip地址换位主机的Ip地址

**Comment by TajangSec** [comment]
老哥可以用QQ交流一下吗，6200674
